### ISSUE TITLE
Upload the File

### ISSUE THREAD

**Issue by victoriagjh** [victoriagjh/SentimentAnalysis#2]
## Todo
- [ ] upload the file to local
- [ ] check the file type(txt, csv,json,excel etc..)
- [ ] display the file at Second Page

## Related Issues
#1 Basic Web Design
