### ISSUE TITLE
Natural Language Process Tools

### ISSUE THREAD

**Issue by victoriagjh** [victoriagjh/SentimentAnalysis#3]
## Todo
- [ ] store the tools that user checked
- [ ] develop each tools functions
- [ ] show the results each tools that chosen by user at second page

## Related Issues
#1 Basic Web Design
